### ISSUE TITLE
time-out for large contribution sets

### ISSUE THREAD

**Issue by Bibiko** [clld/clics#10]
for larger contributions like NorthEuralex http://clics.clld.org/contributions/lexibank-northeuralex or IDS http://clics.clld.org/contributions/lexibank-ids a 504 Gateway Time-out page appears

**Comment by xrotwang** [comment]
fixed: https://github.com/clld/clics/commit/0830b7b5ebb08d20179ba78f4ed24ab2ddfac9f9
