### ISSUE TITLE
upgrade to clld 4.3

### ISSUE THREAD

**Issue by xrotwang** [clld/clics#11]
and then replace the concepticon links with the functionality in `clld.web.util.concepticon`.

**Comment by xrotwang** [comment]
Concept list links on contributions index (see https://clics.clld.org/contributions) and details page (see https://clics.clld.org/contributions/lexibank-allenbai) should be refactored to use `clld` functionality as well.

**Comment by chrzyki** [comment]
Okay, will take care of this.
